/** Core route actions generated by createCoreRouter/Controller (always available). */
export const CORE_ACTIONS = ['find', 'findOne', 'create', 'update', 'delete'] as const;

export const CORE_ACTION_SET: ReadonlySet<string> = new Set(CORE_ACTIONS);

/** A singleType's auto-generated controller serves no `:id` resource → no findOne/create. */
const SINGLE_TYPE_ACTION_SET: ReadonlySet<string> = new Set(['find', 'update', 'delete']);
const NO_ACTIONS: ReadonlySet<string> = new Set();

/**
 * The core CRUD actions Strapi auto-generates for a content-type that has no
 * controller file — by **kind** (a singleType has no findOne/create) and **source**
 * (only `api` content-types are auto-CRUD'd; a plugin author must register its own,
 * so a plugin content-type's auto-CRUD can't be assumed → empty). Used by the
 * validator / resolver to accept a schema-only handler without guessing.
 */
export function autoCrudActions(ct: { kind: 'collectionType' | 'singleType'; source: 'api' | 'plugin' }): ReadonlySet<string> {
  if (ct.source !== 'api') return NO_ACTIONS;
  return ct.kind === 'singleType' ? SINGLE_TYPE_ACTION_SET : CORE_ACTION_SET;
}
